### PR TITLE
Goals schema: expected_sum changed to number

### PR DESCRIPTION
**Pull request by Edke**

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @Edke, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @Edke!

Thank you for signing the Singer Contribution License Agreement.

**Comment by Edke** [comment]
A fix for #4

**Comment by Edke** [comment]
#3

**Pull request merged**
