### PR TITLE
Create product_deals.json

### PR DESCRIPTION
**Pull request by bdemontecler**
Adding product_deals schema for issue #28

### CODE REVIEW

**Comment by cmerrick** [comment]
You did it @bdemontecler!

Thank you for signing the Singer Contribution License Agreement.

**Comment by nick-mccoy** [comment]
Hey @bdemontecler, thanks for submitting this pull request.  To begin with, when submitting PRs, you should include all the relevant changes in a single PR so that it can easily be tested as a single unit of changes.  Your four PRs for this change should actually be 4 commits in a single PR.

Additionally, PRs should only be submitted once they have been tested and proven to work.  We were able to pull in all four PRs and test, and the tap failed.

After inspection, this change is quite a bit more complicated than what you've implemented here.  If you check out the [docs](https://developers.pipedrive.com/docs/api/v1/?#!/Deals/get_deals_id_products) for getting products associated with a deal, the endpoint url includes `/deals/{id}/products`.  This implies that the endpoint depends on knowing the ID of the deal the tap wants to retrieve products for.  So the tap would have to first call out to the [endpoint](https://developers.pipedrive.com/docs/api/v1/?#!/Deals/get_deals) that gets all deals and then cycle over the response and use each deal ID to retrieve the corresponding products.  

This strategy would be tricky to implement given the inheritance pattern this tap uses for streams.  I'm not sure if @Edke, the original author, is still willing to help make additions to the tap, but I think he would be the best source of help/guidance for making this change.

**Comment by bdemontecler** [comment]
Thank you for your understanding, i'm not a developer "pro", i'm learning and i don't find the way to send all my changed in only 1 PR, il will learn :)

I hope @Edke could help us :)

**Comment by nick-mccoy** [comment]
Sounds good @bdemontecler, and no worries!

I'm going to close these four PRs.  If you end up re-implementing this, you can submit a PR at that point.

**Pull request closed without merging**
