### PR TITLE
removed required field from all schemas

### PR DESCRIPTION
**Pull request by bitgo-allenwu**

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @bitgo-allenwu, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by bitgo-allenwu** [comment]
Hey Christopher, you should see my signature now.

**Comment by cmerrick** [comment]
You did it @bitgo-allenwu!

Thank you for signing the Singer Contribution License Agreement.

**Comment by bitgo-allenwu** [comment]
@alewis-ce Per the recommendation of @timvisher in the Slack channel, I removed the "required' field from all the schemas since nothing was really depending on them. (https://github.com/singer-io/tap-pipedrive/issues/31) As soon as this is approved and merged, the ETL bug should be fixed.

**Comment by KAllan357** [comment]
Thanks :+1:

**Pull request merged**
